#!/bin/sh
#
# @name Gazebo x500 custom
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_custom}

. ${R}etc/init.d-posix/airframes/4001_gz_x500
# SLAM Benchmarking Speed Overrides
#

# XY (Horizontal) Speeds
param set MPC_XY_CRUISE 1.5	# Cruise speed
param set MPC_XY_VEL_MAX 2.0	# Max speed

# Z (Vertical) Speeds
param set MPC_TKO_SPEED 1.0	# Takeoff speed
param set MPC_Z_VEL_MAX_UP 1.5	# Max ascent speed
param set MPC_Z_VEL_MAX_DN 1.0	# Max descent speed

# Yaw (Turning) Speed
param set MPC_YAWRAUTO_MAX 10.0	# Max yaw rate
